version: '2'
services:
  backend:
    image: registry.gitlab.com/okaufmann/how-to-not-use-pipelines:$CI_COMMIT_REF_SLUG
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      traefik.frontend.rule: Host:$CI_COMMIT_REF_SLUG-htnup.lab.mighty-code.com
      traefik.enable: 'true'
      traefik.port: '80'
      traefik.acme: 'true'
      traefik.frontend.redirect.entryPoint: https
      traefik.frontend.entryPoints: http,https
      traefik.frontend.redirect.permanent: true
